apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: GATEWAY_PORT
              value: "8080"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: "wallet-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: "http://wallet-service:8082"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: "Path=/api/v1/wallets/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: "auth-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: "http://auth-service:8081"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: "Path=/api/v1/auth/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
              value: "notification-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
              value: "http://notification-service:8083"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
              value: "Path=/api/v1/notifications/**"
            - name: NEXUSPAY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nexuspay-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort